### ISSUE TITLE
Create task xong phải tắt luôn modal. Modal tắt đi phải reset lại dữ liệu, tạo xong bật lại vẫn còn dữ liệu cũ

### ISSUE THREAD

**Issue by datvuhp2002** [chi-cong/project-management-fe#41]
<img width="1500" alt="image" src="https://github.com/user-attachments/assets/ba182bd6-fab5-4523-b094-76508f4efdca">
<img width="1070" alt="image" src="https://github.com/user-attachments/assets/a1a0ddb8-2fd9-46aa-90cd-60aa1e842583">

**Comment by DuonggPh** [comment]
cả trang create project và create department
